name: Api Check 

on:
  push: 
    branches:
      - main 
jobs:
  syntax-check: 
    runs-on: windows-latest 

    steps: 
    - name: Checkout repository 
      uses: actions/checkout@v2 

    - name: Setup .NET Core 
      uses: actions/setup-dotnet@v1 
      with:
        dotnet-version: '8.0.x' 
  
    - name: Restore dependencies 
      run: dotnet restore 

    - name: NuGet package 
      run: dotnet add obrazcova12/obrazcova12.csproj package Microsoft.CodeAnalysis.NetAnalyzers --version 8.0.0 
    
    - name: Run Check
      run: dotnet build obrazcova12/obrazcova12.csproj /p:WarningLevel=6 /p:DebugType=None /p:DebugSymbols-false /p:Platform="Any CPU" /p:TreatWarningsAsErrors=true